spring.application.name=mercadeira.api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mercadeira}
spring.datasource.username=${DB_USER:mercadeira_app}
spring.datasource.password=${DB_PASSWORD:3c5x9cfg@}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
