spring.application.name=mercadeira.api
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mercadeira}
spring.datasource.username=${DB_USER:mercadeira_app}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

mercadeira.jwt.secret=${JWT_SECRET}
mercadeira.jwt.duracao=${JWT_DURATION:PT1H}
